[project]
name = "piyush-data-engineering-journey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Piyush Bhandarkar", email = "piyushbhandarkar9@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
piyush-data-engineering-journey = "piyush_data_engineering_journey:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
